# Generated by Django 3.1.3 on 2021-01-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20201222_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ForeignKey(default=63, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='network.post'),
            preserve_default=False,
        ),
    ]
